--Task 3: Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue.

SELECT c.name AS category_name, SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM Order_Items oi
INNER JOIN Products p ON oi.product_id = p.product_id
INNER JOIN Categories c ON p.category_id = c.category_id
GROUP BY c.name
ORDER BY total_revenue DESC;
